
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RSRawat
 */
public class j2 extends javax.swing.JFrame {

    /**
     * Creates new form j2
     */
    public j2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        j1 = new javax.swing.JRadioButton();
        j2 = new javax.swing.JRadioButton();
        j3 = new javax.swing.JRadioButton();
        j4 = new javax.swing.JRadioButton();
        j5 = new javax.swing.JRadioButton();
        j6 = new javax.swing.JRadioButton();
        j7 = new javax.swing.JRadioButton();
        j8 = new javax.swing.JRadioButton();
        j9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("WELCOME TO  MY TOP 10 ANIME'S");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 424, 63));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*******THIS LIST IS BASED ON MY OPINION AND CAN DIFFER FOR OTHER ANIME WATCHERS *******");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        buttonGroup1.add(j1);
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("DRAGON BALL Z");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 140, 160, -1));

        buttonGroup1.add(j2);
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setText("NARUTO");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 181, 160, 20));

        buttonGroup1.add(j3);
        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.setText("TOKYO GHOUL");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 222, 160, 20));

        buttonGroup1.add(j4);
        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.setText("CODE GEASS");
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 263, 160, 20));

        buttonGroup1.add(j5);
        j5.setForeground(new java.awt.Color(255, 255, 255));
        j5.setText("PARASYTE");
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 304, 160, 20));

        buttonGroup1.add(j6);
        j6.setForeground(new java.awt.Color(255, 255, 255));
        j6.setText("ANOTHER");
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 190, 20));

        buttonGroup1.add(j7);
        j7.setForeground(new java.awt.Color(255, 255, 255));
        j7.setText("KAICHOU WA MAID SAMA");
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 190, 20));

        buttonGroup1.add(j8);
        j8.setForeground(new java.awt.Color(255, 255, 255));
        j8.setText("NISEKOI");
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 190, 20));

        buttonGroup1.add(j9);
        j9.setForeground(new java.awt.Color(255, 255, 255));
        j9.setText("ANOHANA");
        getContentPane().add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 190, 20));

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("SAITAMA:ONE PUNCH MAN");
        getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 190, 20));

        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("1.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 144, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("2.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 185, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("3.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 226, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("4.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 267, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("5.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 308, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("6.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("7.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("8.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("9.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("10.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jButton1.setText("ACCEPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 130, -1));

        jLabel13.setForeground(new java.awt.Color(0, 255, 255));
        jLabel13.setText("----------------------CHOOSE ANY ONE TO SEE THEIR WALLPAPERS---------------------");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 503, 22));

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Working Folder\\Desktop\\cgrrwr2.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(j1.isSelected())
{
    JOptionPane.showMessageDialog(null,"Dragon Ball Z");
    this.setVisible(false);
    J3 j = new J3();
    j.setVisible(true);
}
if(j2.isSelected())
{
    JOptionPane.showMessageDialog(null,"NARUTO");
    this.setVisible(false);
    J4 j = new J4();
    j.setVisible(true);
}
if(j3.isSelected())
{
    JOptionPane.showMessageDialog(null,"TOKYO GHOUL");
    this.setVisible(false);
    J5 j = new J5();
    j.setVisible(true);
}

        if(j4.isSelected())
{
    JOptionPane.showMessageDialog(null,"CODE GEASS");
    this.setVisible(false);
    J6 j = new J6();
    j.setVisible(true);
}
        if(j5.isSelected())
{
    JOptionPane.showMessageDialog(null,"PARASYTE");
    this.setVisible(false);
    J7 j = new J7();
    j.setVisible(true);
}
        if(j6.isSelected())
{
    JOptionPane.showMessageDialog(null,"ANOTHER");
    this.setVisible(false);
    J8 j = new J8();
    j.setVisible(true);
}
        if(j7.isSelected())
{
    JOptionPane.showMessageDialog(null,"KAICHOU WA MAID SAMA");
    this.setVisible(false);
    J9 j = new J9();
    j.setVisible(true);
}
        if(j8.isSelected())
{
    JOptionPane.showMessageDialog(null,"NISEKOI");
    this.setVisible(false);
    J10 j = new J10();
    j.setVisible(true);
}
        if(j9.isSelected())
{
    JOptionPane.showMessageDialog(null,"ANOHANA");
    this.setVisible(false);
    J11 j = new J11();
    j.setVisible(true);
}
        if(jRadioButton10.isSelected())
{
    JOptionPane.showMessageDialog(null,"SAITAMA:ONE PUNCH MAN");
    this.setVisible(false);
    J12 j = new J12();
    j.setVisible(true);
}
// TODO add your handling code here:
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton j1;
    private javax.swing.JRadioButton j2;
    private javax.swing.JRadioButton j3;
    private javax.swing.JRadioButton j4;
    private javax.swing.JRadioButton j5;
    private javax.swing.JRadioButton j6;
    private javax.swing.JRadioButton j7;
    private javax.swing.JRadioButton j8;
    private javax.swing.JRadioButton j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton10;
    // End of variables declaration//GEN-END:variables

    private void setVisible(String afalse) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
