

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RSRawat
 */
public class NewJFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        this.totalprice = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jc1 = new javax.swing.JComboBox<>();
        jc2 = new javax.swing.JComboBox<>();
        jc3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        t9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 0, 279, 115));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 121, 116, 41));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 124, 92, -1));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 168, 103, -1));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 194, 103, -1));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 220, 103, -1));

        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burger", "Veg Roll", "Sandwitch", "Samosa", "Chowmein", "Chole Bhature", "None" }));
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 168, 101, -1));

        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burger", "Veg Roll", "Sandwitch", "Samosa", "Chowmein", "Chole Bhature", "None" }));
        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });
        getContentPane().add(jc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 194, 101, -1));

        jc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burger", "Veg Roll", "Sandwitch", "Samosa", "Chowmein", "Chole Bhature", "None" }));
        jc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc3ActionPerformed(evt);
            }
        });
        getContentPane().add(jc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 220, 101, -1));

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 298, 103, 21));

        jButton2.setText("TOTAL PRICE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 297, 101, -1));

        jLabel1.setText("TAX");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 257, 101, 22));

        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 259, 103, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 530, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed
double price = 0;
String nm = null;
    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed


if(jc1.getSelectedIndex()==0)
{
    price=140;
    
}
else if(jc1.getSelectedIndex()==1)
{
    price=130;
    

}
else if(jc1.getSelectedIndex()==2)
{
    price=30;
    
}
else if(jc1.getSelectedIndex()==3)
{
    price=40;

    
}
else if(jc1.getSelectedIndex()==4)
{
    price=50;
    
            
}
else if(jc1.getSelectedIndex()==5)
{
    price=70;
    
}
else if(jc1.getSelectedIndex()==6)
{
    price=0;
}

t4.setText(price+"ee");        // TODO add your handling code here:
    }//GEN-LAST:event_jc1ActionPerformed

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed

if(jc2.getSelectedIndex()==0)
{
    price=140;
    nm="burger";
}
else if(jc2.getSelectedIndex()==1)
{
    price=130;
    nm="veg roll";

}
else if(jc2.getSelectedIndex()==2)
{
    price=30;
    nm="sandwitch";
}
else if(jc2.getSelectedIndex()==3)
{
    price=40;
    nm="samosa";
    
}
else if(jc2.getSelectedIndex()==4)
{
    price=50;
    nm="spinach";
            
}
else if(jc2.getSelectedIndex()==5)
{
    price=70;
    nm="chole Bhature";
}
else if(jc2.getSelectedIndex()==6)
{
    price=0;
}

t5.setText(price+"");        // TODO add your handling code here:
    }//GEN-LAST:event_jc2ActionPerformed

    private void jc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc3ActionPerformed

if(jc3.getSelectedIndex()==0)
{
    price=140;
    nm="burger";
}
else if(jc3.getSelectedIndex()==1)
{
    price=130;
    nm="veg roll";

}
else if(jc3.getSelectedIndex()==2)
{
    price=30;
    nm="sandwitch";
}
else if(jc3.getSelectedIndex()==3)
{
    price=40;
    nm="samosa";
    
}
else if(jc3.getSelectedIndex()==4)
{
    price=50;
    nm="spinach";
            
}
else if(jc3.getSelectedIndex()==5)
{
    price=70;
    nm="chole Bhature";
}
else if(jc3.getSelectedIndex()==6)
{
    price=0;
}


t6.setText(price+"");        // TODO add your handling code here:
    }//GEN-LAST:event_jc3ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed

    }//GEN-LAST:event_t9ActionPerformed
int r,s,t,w; float totalprice; float tax;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
r=(int) Double.parseDouble(t4.getText());
s=(int) Double.parseDouble(t5.getText());
t=(int) Double.parseDouble(t6.getText());
tax=(float) ((r+s+t)*0.14);
totalprice=r+s+t+tax;
t10.setText(tax+"");
t9.setText(totalprice+" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed

    }//GEN-LAST:event_t10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
NewJFrame3 j2= new NewJFrame3();
j2.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JComboBox<String> jc3;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
